name: Temp job

# Controls when the workflow will run
on:
  workflow_dispatch:

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        run: echo hello

